# Generated by Django 5.1.4 on 2025-01-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_reposts_repost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repost',
            name='reposted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
