# Generated by Django 5.1.5 on 2025-02-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_repost_reposted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='old_content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
