# Generated by Django 5.1.5 on 2025-02-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='target_content_type',
            new_name='content_type',
        ),
    ]
