# Generated by Django 5.1.5 on 2025-02-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_target_content_type_notification_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='target_object_id',
            new_name='object_id',
        ),
    ]
